import streamlit as st
import os, io, json, base64, re
from datetime import date

try:
    from openpyxl import Workbook
    from openpyxl.styles import Font, Alignment, Border, Side
    from openpyxl.drawing.image import Image as XLImage
except ImportError:
    st.error("pip install openpyxl"); st.stop()

try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import cm, mm
    from reportlab.lib import colors
    from reportlab.platypus import (BaseDocTemplate, Frame, PageTemplate,
                                     Table, TableStyle, Paragraph, Spacer,
                                     Image as RLImage, HRFlowable, KeepInFrame)
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont
    HAS_PDF = True
except ImportError:
    HAS_PDF = False

# ── Logo ──────────────────────────────────────────────────────────────────────
LOGO_B64 = (
    "/9j/4AAQSkZJRgABAQEAYABgAAD/4RDyRXhpZgAATU0AKgAAAAgABAE7AAIAAAANAAAISodpAAQAAAAB"
    "AAAIWJydAAEAAAAaAAAQ0OocAAcAAAgMAAAAPgAAAAAc6gAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEF5Y2FuLCBG"
    "YXRpaAAAAAWQAwACAAAAFAAAEKaQBAACAAAAFAAAELqSkQACAAAAAzg5AACSkgACAAAAAzg5AADqHAAH"
    "AAAIDAAACJoAAAAAHOoAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyMDIyOjExOjAxIDA5OjMzOjQ4ADIwMjI6MTE6"
    "MDEgMDk6MzM6NDgAAABBAHkAYwBhAG4ALAAgAEYAYQB0AGkAaAAAAP/hCx9odHRwOi8vbnMuYWRvYmUu"
    "Y29tL3hhcC8xLjAvADw/eHBhY2tldCBiZWdpbj0n77u/JyBpZD0nVzVNME1wQ2VoaUh6cmVTek5UY3pr"
    "YzlkJz8+DQo8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIj48cmRmOlJERiB4bWxuczpy"
    "ZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPjxyZGY6RGVzY3Jp"
    "cHRpb24gcmRmOmFib3V0PSJ1dWlkOmZhZjViZGQ1LWJhM2QtMTFkYS1hZDMxLWQzM2Q3NTE4MmYxYiIg"
    "eG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIi8+PHJkZjpEZXNjcmlwdGlv"
    "biByZGY6YWJvdXQ9InV1aWQ6ZmFmNWJkZDUtYmEzZC0xMWRhLWFkMzEtZDMzZDc1MTgyZjFiIiB4bWxu"
    "czp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iPjx4bXA6Q3JlYXRlRGF0ZT4yMDIyLTEx"
    "LTAxVDA5OjMzOjQ4Ljg4OTwveG1wOkNyZWF0ZURhdGU+PC9yZGY6RGVzY3JpcHRpb24+PHJkZjpEZXNj"
    "cmlwdGlvbiByZGY6YWJvdXQ9InV1aWQ6ZmFmNWJkZDUtYmEzZC0xMWRhLWFkMzEtZDMzZDc1MTgyZjFi"
    "IiB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iPjxkYzpjcmVhdG9yPjxy"
    "ZGY6U2VxIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5z"
    "IyI+PHJkZjpsaT5BeWNhbiwgRmF0aWg8L3JkZjpsaT48L3JkZjpTZXE+DQoJCQk8L2RjOmNyZWF0b3I+"
    "PC9yZGY6RGVzY3JpcHRpb24+PC9yZGY6UkRGPjwveDp4bXBtZXRhPg0KICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAK"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg"
    "ICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8P3hwYWNrZXQg"
    "ZW5kPSd3Jz8+/9sAQwAHBQUGBQQHBgUGCAcHCAoRCwoJCQoVDxAMERgVGhkYFRgXGx4nIRsdJR0XGCIu"
    "IiUoKSssKxogLzMvKjInKisq/9sAQwEHCAgKCQoUCwsUKhwYHCoqKioqKioqKioqKioqKioqKioqKioq"
    "KioqKioqKioqKioqKioqKioqKioqKioqKioq/8AAEQgAyQMZAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEB"
    "AAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQy"
    "gZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hp"
    "anN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY"
    "2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALUR"
    "AAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEX"
    "GBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWW"
    "l5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/a"
    "AAwDAQACEQMRAD8A+kaKKKACiiigAooooAKKKKACiiigAooooAKKKKACikLAAknAHUmoUvrWR9iXMTN/"
    "dDgmnZvYTkluyeijNFIYUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABR"
    "RRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABR"
    "RRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABR"
    "RRQAUUUUAFFFFABRRRQAUUUUAFFFFABQelFR3DBLaVmOAqEk+nFAm7K55p4n8SXGp3slvA7R2kbFQqnG"
    "/Hc1z4JByCQfWkzk5NFfXU6cacVGKPzetWnXqOpN6s7jwZ4kmmuBpl/I0mV/cyMckY/hNdxXk3haJ5vE"
    "1mI8/K+4kdgBzXrNeDmFOMKvu9T7DJq1Srh3z62dgooorzz2QooooAKKKKACiiigAooooAKKKKACiiig"
    "AooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiig"
    "AooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiig"
    "AooooAKKKKACiiigAooooAKKKKACiiigAooooAKKK5PW/iHpWkXL20Ye8nThhFjap9M/4VpTpzqO0Fcz"
    "qVYUlebsdZRXE6b8T9Ku7hYryGWz3HAkb5lH1x0rtEdZEV42DKwyGU5BFOpRqUnaasKnWp1VeDuOopks"
    "0cMTSTOqIoyzMcAVzF14/wBOhkK28M1wB/EPlB/OinRqVfgVyK2Jo0F+9lY6quU8aa+lnYvp9u4NxOuH"
    "wfuKev4msvUPiBPNAY9Pt/IZhgyOdxH0FY2i6VLr2oyPcyssMY8y4nY9B9fWvQoYN037WtokeLi8yVZe"
    "wwurl1KFnp93qEhSyt5JmHXavA+p7VqReDdblcBrQRj+88i4H5GrF544Fips/DdrFBbpwJXXLN74/wAc"
    "1FY/ETVIZh9uSK5iJ5AXaw+hHH6V6EpYqSvCKXrueTChgItRqzbfdbf5nZ+G/DUehxM7sJbqQYZwOFHo"
    "K3ap6Zqdtq2nx3dm26Nx0PVT3Bq5Xz1WU5TbnufY4enSp0lGl8IUUUVmbhRRRQAUUUUAFFFFABRRRQAU"
    "UZooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiijNABRRRQAUUUUAFFFGaACiiigAooooAKKKK"
    "ACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKK"
    "ACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAOe8c6nLpXhO5lt2KSyERKw6jd1P5Zrw"
    "889a9y8Z6VJrHhe5t7dd0y4kjUdyvb8s14cylGKsCGBwQexr38s5fZO29z57NOb2qvtYSvVvhfq0t3pN"
    "xYTuX+ysDHk8hT2/P+deU12Xwy1BbTxO1tI2Fu4ii57sOR+ma6MbT56EvLU58DU5K8fPQ6f4g6hIpt7C"
    "NiqMPMkA/i7AVw9dz8QNOkcW+oRqWRB5cmP4fQ1w1TgeX2C5Tzc25/rcub5egV1rqbH4XSPCNr3Un7xh"
    "1ILY/kMfjXKJG8sixxqWdiAqgZJNeproKzeEF0i4+VjCASP4X65/OpxlWMOS/dP7jXKqEqrqOP8AK182"
    "eOUVb1HTbrS7tre9iaN1PBI4YeoPeqlekmpK6PNlFxdpLU7z4aXpE97YseColUemDg/zFehV454R1JdM"
    "8SW8srbY3zE5PQA//XxXsdfOZjT5a3N3PsMnq8+G5f5WFFFFeaewFFFFABRRRQAUUUUAFFFFAHh0vxf1"
    "jQtT1LTntob1Yb2ZY5JWIZV3nC8dcUn/AAvfVv8AoE2f/fbVpn4Ly6vqF/f6lqTWj3F5NIkSRh8IXJBJ"
    "z1I5p3/Chbb/AKDkv/fgf419Dz5d9pa/M+c5My+y9PkZX/C99W/6BNn/AN9tR/wvfVv+gTZ/99tXO/ED"
    "wNH4Jnso4r1rv7SrMS0YXbgj3965zRdPGra5Z6e0hjFzMsZcDO3JxmuuGFwc6ftIx0+ZxzxWNp1PZylr"
    "8j0X/he+rf8AQJs/++2ob47auVONKswccHe3Fav/AAoW2/6Dkv8A34H+NDfAW32nbrsuccZtx1/OuTny"
    "zt+Z2cmad/yO4+Huo3OreBrG+v5TLcTmRnY+vmNXS1z/AIG0e50HwdZ6ZfBRPbmRW2nIPzsQR9QQa6Cv"
    "Er8rqy5drs92hzKlHm3shGztO3Ge2a8j134waz4f1u50u90WzM1u+1ik7FW4yCOO4Ir1LVdSg0jSbnUL"
    "ttsNvGZG98DpXyjrGqT61rN1qV2czXMpkbHQZ6AewHFejlmGjWcnUV0vzPMzTFToKKpys3+R6dF8ddSm"
    "lSOPQ7Yu7BVHntyT+FeyWTXT2UTX6Rx3JUGRImLKp9AT1r5BBIORwa+nPh54lXxP4Rtrl33XUI8m5Hfe"
    "O/4jBrXMsJClBSpRsupllmMnWnKNWV30Opooorwz3gooooAK87+J3i7UfCGo6Rd6cVdJBIssEmdkg4xn"
    "3HrXolcL8QfBN1401LSoY5Rb2sAkaacjcVzjAA7k11YR01WTq/Drf7jkxiqOi1S+LS33nEf8L31b/oE2"
    "f/fbUn/C99W/6BNn/wB9tWr/AMKFtv8AoOS/9+B/jVXVfglb6do95errMshtoHmCGADdtUnHX2r2FLLG"
    "7JfmeM45oldv8ip/wvfVv+gTZ/8AfbUf8L31b/oE2f8A321eWV6Z4O+E8HinwvbatJqklu0zOPLWIMBt"
    "Yr1z7V01sNgqEeapGy+Zy0cTjq8uWnK7+RP/AML31b/oE2n/AH21a/gn4h6p4x8f2sFyiWtrFbyt5MRO"
    "HbA5OeuO1N/4ULbf9Byb/vwP8a0fCnwyuPB/je2vre6+2WbQSJI5UK0bEDHGeQa4qk8B7OXs/is7b/qd"
    "9OGYe0j7X4bq+36HplFFFeCe+FFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABWL4s1bUND8PXGpaZa"
    "w3TWymSWOVyvyDqQR3HWtqvN/jN4jGmeGV0mCQfaNROHAPIiHU/icD866MNTdStGFr6nPiqipUZTvbQ5"
    "r/hfOof9AS2/7/N/hXSeCPiTq/jLXDaR6VaQQQr5k8pmYlVzjgY5NeB10fgPxI/hfxba3u7FvIfJuF9Y"
    "26/kcH8K+jr5fR9lL2cdem58zQzGv7WPtJ+7fXY+oqKajB1DKcqwyCO9Or5Q+uCiiigAooooAKKKKACi"
    "iigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigArndY8D6NrNw0"
    "88LQzty0kJ2lj6kdK3bq5hs7WS4uXEcUSlnY9gK8s1v4m6hcXLJowW2t14V2Xc7+/PArrwtKtOV6Wnmc"
    "eKq0IRtVV/I0b74TpsJ03UmDdknTIP8AwIdPyri9S0bVfC+oRNdRtDIrBopkOVJBzkGtvTPiVrNrcL9v"
    "KXkGfmUqFbHsR/WvR5E07xh4a4xJb3CZUkcxt/Qg16DrYjDNKtrFnnKjh8Sm6GkkZHh/xzpeuWS22qvH"
    "bXTLtkSU4ST3BPHPoasXHgPSriTzInmhVudsbAj9Qa8cvLWSxvp7WYYkhkaNvqDipbXVL+xAFne3EAHa"
    "OQgflW31NxfNQna5zvFQqJRxMOa33ntuleF9O0iQSwRtJMOkkhyR9PStntXk3hn4iX1rexwa3N9otXO0"
    "ysPnj98jqK9VlnjhtnndgI0QuWzxgDOa8nE0q0J/vHe57GEqUHT/AHSsl0G3Fpb3cfl3cEU6f3ZEDD9a"
    "x7rwZoVyp/0JYif4oiV/+tXDa14lvdWuHxK8Vtn5IkOOPf1NZtre3VlKJLSeSJs5yrYzXdSwNaMbqdme"
    "LXzfDTnZ0+Zd9P8AL9TW8SeCZ9Hja6snNxaLy2fvR/X1HvVrw749exhS01ZGmhQYSZeWUeh9a6nwzrY8"
    "QabJHdqpnjG2VccOD3xXmWvaeNL1y6tE+5G52Z/unkfpW9F/WL0MQtUZV7YXlxWEdoy6Hqlt4t0O5AKa"
    "hEhPaT5f51rRTRTxiSCRJEPRkYEH8RXgtaOi63d6JerNayHZn95ET8rj6f1rOplatenLXzNqOdy5kqsd"
    "PI9srP1LXdO0nH2+6SJiMhOrH8BTL7WI7fw3JqsXzJ5IkTPfI4/UivGrq6mvbqS4upDJLIcsxNceEwft"
    "23LRI9DH5j9WSUFdvX5Hrdr4y0O7mEUd4EYnA8xSoP4mt0EHpzXgVejfDzW5buCXTbli5gUPExPO3pj8"
    "K2xeAVKHPB7HNgM1lXqeyqrV7WO3oooryT3wooooAKKKKAPF/j1/x+6P/wBc5P5ivPPB3/I66R/19x/z"
    "r0P49f8AH7o//XOT+Yrzzwd/yOukf9fcf86+swf+5L0f6nyGM/35+q/Q+q6KKK+TPrwooqvfXsOn6fPe"
    "XLbYYI2kc+gAzTSbdkJtJXZ5X8bvExhtbfw9bPgzYmucH+EH5V/MZ/AV5x4E8O/8JN4utLF1LW6nzbj/"
    "AK5r1H48D8az/EOsz+IPEF3qd0TvuJCwH91eir+AwK9q+DHhsab4ZfVp0xcagcoSOREOn5nJ/Kvp52wO"
    "Dsvi/V/5HysL4/G3fwr8l/mea/FDw2PDvjGb7PEI7O8HnwbRhRn7yj6Ht6EVb+EniddC8WCzuZNlpqOI"
    "mJPCyfwH8zj8a9P+LHh3+3fBks8KbrnT8zx4HJUD5x+XP4V86KxRgynDKcg+lXhZLGYXklvs/wBGTioS"
    "weL54bbr9UfYlFcx8P8AxMnijwlbXTNm6iHk3I7hwOv4jB/Gunr5epCVOThLdH1VOcakFOOzCiiioLCi"
    "iigArL8T/wDIo6x/14z/APos1qVl+J/+RR1j/rxn/wDRZq6fxr1IqfA/Q+Ta+kPhF/yTPT/9+b/0a1fN"
    "9fSHwi/5Jnp/+/N/6Navpc2/3dev6M+Xyf8A3h+n6o7ag0UV8ufVnCa78WNJ8OaxNpupabqSzxHkqkZV"
    "gehB39DWd/wvTw7/ANA/VP8Av3H/APF1wPxj/wCSiz/9cI/5V3Hgj4c+GdY8Fabf6hYNJcTxlpH81hk7"
    "iOgPtXuSw+EpUIVaievY8GOIxdXETpU2tO5N/wAL08Of9A/VP+/cf/xdMk+OmhGNhb6bqLS4+QOqKpPu"
    "QxwPwrb/AOFTeD/+gY3/AH/f/GmTfCPwjLCyx2UkLkfLIkzZU+vJxWHNl/8ALL+vmdDhmP8ANH+vkdnb"
    "yebbRyEYLoGI+orj/EfxS8PeHLl7V5JLy6jOHitgDtPoWJAFX/G99PoXw+1G4s3KzQ26ojjggkhc/rmv"
    "Cvh74XtvF3ij7HqF0YYY4zM4VsPLggbQT9aWEwtOpCVaq/dQ8ZiqtOcaNJe8zvv+F82nmY/sKfZnr9oG"
    "fy2/1rf0n4w+GNSZUuZJ9Pc/8/CfL/30uatJ8KPB6QhP7MLcY3NM5P55rlfFvwVtvsb3XhSSVJ0BJtJW"
    "3B/ZWPIP1z+FWv7PqPlScfP+rmb/ALRpLmbUvL+rHea/4stNM8L3er6dNb3/ANmVJCkcobKlwOx46muT"
    "Hx08PYGdP1PPf5I//i6t+E/h5DB8N30nUQ8NxqZWW8IHzKAwIT2wBj6k1eHwl8HgY/s1j9Z3/wAayj9T"
    "heM7uz3XY2l9dqcsqdldbPuY/wDwvTw7/wBA/VP+/cf/AMXR/wAL08O/9A/VP+/cf/xdec/FDw/p3hvx"
    "WlnpEJhga3WQqXLckn1+ldz8Pfh74b13wVaX+p2JluJC+5xKwzhiBwDXbUw+Cp0VWadmcNPEY6pWlRTV"
    "0bGkfF3S9e16x0vTbC8WW6l2F7gKqqME54Y5PFeg1yFl8MvDumatZ6jpcEltcWsm9SJCwbggggn3rr68"
    "nEOg5L2KaXmexh1XUX7dpvyCiiiuY6RruqIzuwVVGSScACvlzxz4hPifxbd36kmAHyoAe0a9Pz5P417L"
    "8XvEo0XwmbCF8XWpZiUA8iMffP6gfjXg2kaZca1rFrp1mu6a5kEa+2epPsBzX0OVUVGDry/pdT5zNq7n"
    "NUI/0+h6L8Pvh4mveCtVvb6PEl2hisWI5Urzv+hYAfQGvMZoZLe4khmUrJGxVlPYg4NfW2k6bBpGkW2n"
    "2oxFbxiNeOuB1/GvCfjF4bGkeKhqVsm221IbyAOFkH3vz4P4mrwWNdXESjLZ7f16EY7Aqlh4Sjut/n/w"
    "T0P4ReJzrnhQWV1Juu9OxESTy0f8B/IY/Cu/r5f8A+JW8L+Lra8d9ttIfJuR2KHv+Bwfwr6fUhlBU5BG"
    "QRXm5jh/Y1rrZ6/5np5biPbUbPeOn+Q2RikbMqFyASFXGW9ua8/ufjP4etLqW3uLTUklico6+UnBBwR9"
    "6vQ6+T/E4z4u1UDk/bJP/QjTy/DU8RKSn0JzHFVMPGLp9T6f0HWrfxDosGqWaSJBOCUEmN2AcdifStGv"
    "m74feP7nwjqAt7otLpczfvYs8xn++v8AUd6+irO8t7+ziurOVZoJlDpIhyGBrHGYWWHn5PY3wWLjiaf9"
    "5bnO+K/HuneD7qCLVbW8IuFJikiRWVsYyOWHTI/OrvhbxTa+LNPe+0+3uYrdX2B51Ubz3xgnpXnHx9/5"
    "gH/bz/7Srpfgz/yT2L/r4k/nWs8PTWDjWW7f+ZlDEVHjZUH8KX6L/M76sjxP4hg8L6K+qXltcT28bKJP"
    "ICkpk4BIJHGSB+Na9ePfHDxJhLXw9bvy2Li5APb+FT+px9K58LR9tWUOnX0OnF1vYUZT69PU2rX416Fe"
    "3cVtbaZqjyzOERfLj5JOB/HXoykkAkEcdD2r5JuLC/0f7DdTxvAbiMXNs/crnhv0z+VfTHgrxGnijwra"
    "6hwJyuy4UfwyDg/gev4124/BwoxjOlscOX4ypWlKFXfob5rifEvxQ0vwrrLabqen6gZQgdXjWMq6noRl"
    "wex/Ku2r5/8Ajd/yPsX/AF4x/wDoT1zYCjCvW5J7WOnMK86FHnhvc9n8MeI4fFOkLqVpaXNvbyMRGbgK"
    "C+DgkAE8ZBFbNcl8Lv8Akmmkf7j/APoxq62uatFQqyjHZNnTQk50oylu0grn/Fni238IWcd3f2V3Pbu2"
    "wyW4QhD2BywroK4v4o6Pea94VSw04xm4e5UqkkgTzMAnAz3qsPGEqsVPYWIlONKUob9CTwr8RtO8Yak9"
    "nplhfIY03ySTKgVR+DE1B4r+JNn4O8Rpp2pWc80Mlok6SW+CwYu6kEEgYworl/g5oWqaH4i1WHV7Ce0c"
    "26481CA3zdj0P4V3Ou+AdF8S62NS1mOSdkt1gSMOVCgMzZ46k7v0rrqww1LEOL1hbocVKeKq4ZSWk79T"
    "mf8Ahenh3/oH6p/37j/+Lo/4Xp4d/wCgfqn/AH7j/wDi62P+FTeD/wDoGN/3/f8Axryz4nWPhjQ75NI8"
    "PWQW6jO65m81m2ccIATjPOT+FdNCngq8+SEZHNXq47Dw55yj/XyO7/4Xp4d/6B+qf9+4/wD4uvQdLvhq"
    "el296sMsC3EYkWOYAOoPTIBNeF/CjwKdf1IavqcOdNtW+VXHE0g7Y7gd/wAvWvfwMVy46nQpT9nS36nX"
    "gKmIrQ9pV26BRRRXnHpBRRRQAUUUUAFFFFABRRRQByHxLuHg8IMqHHnTojfTk/0rx2vRfinrKSPbaTCw"
    "Yxt502OxxhR+RP5ivOq+ky+DjQV+p8zmE1Ku7dNAr1D4TzyNp9/ASTGkqso9CRz/ACFea2tpcX1wsFnC"
    "80rHAVFya9r8G+HT4d0MQzENczN5kxHQHHCj6f41OY1Iqjyvdl5dTk63OtkecfEa1Fv4yndVwJ40k/HG"
    "D/KuVr2Xxx4SbxDaJcWeBe24O0E4Ei/3c+vpXklxpd/aTGK5s545AcFWjNaYOtGdJK+qM8bQnTqt20ZV"
    "r2K5mkHwtid2Ika2iUk9wSB/KuH8L+B77WrtJL2GS2sVOXdxtL+yg/zrq/G2rwrDHo9ljZHgybei46LW"
    "WIkqtaFOOtndijehhqlSel1Zedzi6Knt7K6u8/ZbeWbHXYhNaFp4X1i7lVFspIweryjaB+dd0qkI/E7H"
    "zsKNWp8EW/ka3w9VzrFy4z5Yt8N6ZLDH8jVL4i2jQ+II7jadk8Qw3YkcEfyrutA0OPQ7DyVbzJXO6R8Y"
    "yf8ACpNc0S313TzbXOVIO6OQdUb1rxPrcVivadNj6yOXzeAVF/Fv8+x4nS11F38Ptagm22yRXKZ4dZAv"
    "5g4rU0bwGLFxfeIJ4lih+cxK3HH94/0FevLGUIx5lK54cMvxMp8ri15vYt6uv2L4VxQXB2yvHEoU+u4N"
    "j8gfyrzeuj8WeIjr2oLDagi0hO2Jf75/vY/lU2meANVv4RLOY7NG5AkyWP4Dp+NZUGsPS5qrs27m2KUs"
    "XWUaCuopL7jlq7r4a2Mhurq+ZSIlTylb1YnJ/L+tTWnwzCzA3t/vQHlYkwT+Jrt7OzgsLRLa0jEUUYwq"
    "iuXGY6nKm6dPW53ZdltWFVVaqtYnooorwz6YKKKKACiiigDxf49f8fuj/wDXOT+Yrzzwb/yOukf9fcf8"
    "69D+PP8Ax+6P/wBc5P5iuA8Df8j3o3/X2n86+swn+4r0f6nyOM/39+q/Q+p6KKK+TPrgryv42eJTZ6TB"
    "oVtJtkuz5k+D/wAsweB+J/8AQa9PubiO1tpbidgkUSF3Y9gBkmvlbxTr03iTxLeanOTiZ8Rr/dQcKPyr"
    "1csw/tK3O9o/meTmmI9lR5FvL8upkV01v8RfFVrbx29vq8kcUShERUUBVAwAOK9F+Dng61bRJda1Ozjm"
    "e5Ypb+cgbag4JAPqf5V6X/YWk/8AQMs/+/C/4V6GJzCjGo6coc1jzsLl1aVNVIz5bnzk3xL8XMpDa1MQ"
    "RggovP6VyxJLEnqa+tv7C0n/AKBln/34X/CuA+Lfg21uPC/9qaXZxRT2B3SCGMKXjPXp6dfpmpw+Y0XU"
    "UIw5bjxOW11Tc5T5rHD/AAi8TjQ/FQsbl9trqOIiSeFk/hP9Pxr6Gr47R2jkV0JVlOQR1Br6f8BeJl8U"
    "+Era8YgXMY8q4XPRx3/Hg/jWObYe0lWXXRm+T4i8XRl01R0tFFFeEe+FFFFABWX4n/5FHWP+vGf/ANFm"
    "tSsvxP8A8ijrH/XjN/6LNXT+NepFT4H6HybX0h8Iv+SZ6f8A783/AKNavm+vpD4Rf8kz0/8A35v/AEa1"
    "fS5t/u69f0Z8vk/+8P0/VHbUGig18ufVnzr8Y/8Akos//XCP+VVtH1zx9a6Rbw6KNT+wouIfJtSy4yeh"
    "2885qz8Y/wDkos//AFwj/lXrnw2uYE+HOjq88asITkFwCPnavpalZUcHTbipbb+h8vToutjKkVJx329T"
    "ySXxJ8TPKfzDrCpg7j9jIwPrt4r3DwhI8vg3SXmZnka1jLMxyScd60/tdt/z8Rf99imfa7KCH/j4gjjQ"
    "Z++AAK8jEYhVoqKgo+h7OHwzoScnUcvUr6/pEevaDeaXO21LmIpux909j+Bwa+bdb8FeIvDV8y3FjcFU"
    "PyXNupZGHqGHT6Hmvo/WdcttJ8NXOsF1eGKDzUPZ8/d/MkfnXMeCfiZpfiDToYdUu4bPVFGJI5DsWQ/3"
    "lJ459O1bYKtXoQlKMbxvqYY2jQr1IxnK0raHiEHivxLp2Fi1e/hx2Mrf1rc0r4ueK9OnU3F4l/ED80Vx"
    "GOR/vDBz+NfQctnp95Hvmt7adD/EyKw/OvG/i/F4Ttre2h0eG1TVPMy/2QAAJj+PHGc4x3ruo4qjip+z"
    "lS3OCthK2Fh7SNXY9Q8IeK7Txfoa39oPLdW8uaEnJjf09xg5Brfrx/4DRTiDWJSD5BaNQexbBP8AI/rX"
    "sFePi6UaNeUI7I9rB1ZVqEZy3Z8//G3/AJHqL/r0T+Zr034Tf8k3sP8Aek/9CNeZfG3/AJHqL/r0T+Zr"
    "0z4Tf8k4sP8Aek/9CNeniv8AcKfy/U8zC/8AIwqfP9DtKKKK8I94KRmCgknAHJJ7UtcR8VfEw8P+D5YY"
    "Xxd3+YIgDyFx8zfgOPqRWlKnKrNQj1MqtSNKm5y6HjPxD8SDxP4wubmF99pCfJtz2KDv+JyawtL1a90W"
    "/W90ycwXCAhZAASM9etR2FlPqWoQWVom+e4kEca+pJxX1Bovg/SNI0a2sRYW0phjCvK8Kku3djx3NfU4"
    "jEUsHTjTtfy8j5TDYerjakql7efmeBf8LM8X/wDQbm/75X/Cs7WfF2ueILVLfWL97qJH3qrqowcYzwPe"
    "vp3+wtJ/6Bln/wB+F/wpP7C0n/oGWf8A34X/AArzo5lQi7ql+X+R6UssxElZ1br5/wCZ8lV9EfCTxN/b"
    "vhJbS4k3XenYifJ5ZP4D+Qx+FeV/FHwsnhrxY7WkeyyvQZoVHRD/ABKPYHp7EVS+H3iT/hGPF9tdSPtt"
    "ZT5Nx6bG7/gcH8K9HFU44zDc0PVf5Hm4WpLBYrln6P8AzPp6vlnU/wDko1x/2Ez/AOjK+pVYMoKkEEZB"
    "HevlrU/+SjXH/YTP/oyvMyn4p+h6mb/DT9T0X4ofDTcJde8O2/zAF7q2j7+rqPX1A+tcr8OviFL4SvPs"
    "eobpdKmb5l6mBv7yj+Y/yfoojPvXjXxQ+GhjaXXvD0A2feurWMdPV1H8x+NPCYqFaH1fEbdH/X4BjMJO"
    "jP6zh9+q/r8Rvx0uYby18N3FrKk0Mq3DpIhyGB8rBBrqvgx/yTyP/r5k/nXgM2oXVxp9vZTzM9vas7Qo"
    "38BbG7H/AHyK9++DP/JPI/8Ar4k/nW2Mo+wwSp3vZ/5mGCre3xzqWtdf5Ha6lfwaXplxfXbhILeNpHJ9"
    "AM/nXzVYW938QPiGokyWvrgySn+5GOT+SjH5V6L8bvEgg0+38P28n7y4ImuAD0QH5QfqRn8K4rwv8M/E"
    "2u6Wmq6ZPb2UUuRG00zozqD1G1Txkd/SlgacaFB1puzlomx4+pKviFRgrqOrSPSvix4Uj1HwWlxZRBZt"
    "JAZFUdYsYZfwAB/D3rhPg54oOk+JG0m4fFrqOAuf4ZR90/iMj8quN8H/ABq6lX1izZSMEG7mOf8AxyuE"
    "1zRNS8I68bO9Kx3UBWRJImJU9wynit8PTpToyw/Opf1/mYYipVhXjifZuP6/0j6ur5/+N3/I/Rf9eMf/"
    "AKE9ex+DfEKeJ/C1pqQ2iVl2TqP4ZBw3+P41458bv+R+i/68Y/8A0J68/LYuGKcZbq56OZzU8IpR2bR6"
    "f8KAR8MdJ3Ajibr/ANdnrsa434X3duvw20lWniDKkgILjI/eNXWfbLb/AJ+Iv++xXBiU/bz9X+Z34Vr2"
    "EPRfkTV578Z5pbbwXBNbyNHLHexsjocFSAeQa7mbUbKCF5ZruFI0UszGQYAFcD8aJEm+H8MkTbke6jZW"
    "HcEHFaYNP6xC/cjGyX1eduxofDXxyPF2lGC7+XUrRR53HEg6Bx/UV29eI/Af/kNar/17p/6FXr+t6zaa"
    "Bo8+pahII4YVyfVj2Ue5PFVjaKhiXCmv6ZGBruphlUqP+kc/8RPGsXhHQz5JDajdApbp/d9XPsP1NeE+"
    "FvDt9418TC1V3PmMZbq4POxc8sT6nP5motd1nUPGfidrqbLzXDiOCIHhFzhVFe++BfDen+D9AS2FxBJd"
    "zYe5lDj5m9B7CvU0y/D2Xxy/r8DylfMcRd/BH+vxOi0vTbXR9NgsNPiEVvAgVFH8z6n3q3UP2y2/5+Iv"
    "++xT4Z4rmFZbeRZI2+66HIP418++Zu7Poo8qVkPoooqSgooooAKKKKACjIHXiivIfHfi251DUp9Ns5Wi"
    "soW2OFOPNYdc+2e1dGHw8q8+VHNiMRGhDmkeoSa3pcRIk1G1UjqDMvH61ynib4jWdnA0GiOLq5YY80D5"
    "I/f3NeT0+CFri4jhjGXkYIv1JxXsU8upwd5O549TMqs1yxVje0Dw9d+J72W7vJzFaod1zdyt37jJ6muu"
    "t9T8A6IBbwwx3TDhpWg80n3yR/KsXxzP/Y9rZ+GrBiltDEJJscGVz3P8/wD9VcVWipvEx5pNqPRL9TJ1"
    "FhpcsUnLq3+h7zoWp6HqEROhtbjAyyRxhGH1GBWxXzvp2oXGl6hFeWchjlibII7+oPsa+gNPu1v9Nt7t"
    "Puzxq4/EZrysZhfYNNO6Z6+CxXt001ZofcXMNrA01zIsUa9WY4Arnrjxzo0bEKJ58d0jGP1Irm/G+qSX"
    "estZqx8m2wMdixHJ/XFczXVh8BGUFOp1PGxucVIVXTopWWlzsdW8ey3ETQ6VC1uG481yN2PYDpVDwz4c"
    "Osyvd3zMtpGfmYnmQ9xn+Zrna7vxNIdG8B21pakp5wWNiPQjLfnXTUgqCjSo6OT3OOhUli5yr4l3UFe3"
    "5IS98d6bpJFno9oJ0j43Kdifh3P1p2mfEa0ubgRajbNahjgSK25R9fSvNqStP7PoONmte4f2tiVK6at2"
    "toe+I6ugZCGVhkEHgisnxB4ktPD9sGnzJO4/dwqcFvc+g96yfh5fvdaFJbytuNtJtXPZTyP61xvjO4ku"
    "PFd55hJEbCNR6ACvLoYNSxDpz2R7mJzBwwka1Nay/A0pfiPqjSExQW6L2BBP9axNW8R6nrWBe3BMY6RI"
    "Nq/l3/GsqlUbmA9TXuQw9Gm7xij5ipi8RVXLObaPRPAvhmOO2TVr6MNLJzArfwr/AHvqa7nFQ2caxWMC"
    "IMKsagD8Kmr5ivVlVqOUj7bC0IYekoRCiiisDpCiiigAooooAKDRRQB5V8R/BvijxjrETWdraR2dqCkL"
    "PcfM+epIxx06VzOlfCjxjpOrWuoQRWLSW0qyKGuOCQenSve6K9CnmFWnT9nFKx51TLqNSp7STdyC0eeS"
    "0ie7hWGdkBkjV9wVu4B7ip6KK889E4r4hab4o17T5NI0CC3S0mUefPJPtduc7QMcDgZ9eleXf8KX8Wf3"
    "LP8A8CP/AK1fQ1Fd9HHVaEOSCR59fL6VefPNu5geDLbV7Dw3b2GuW1vBLaIsMZt33K6AYBI7H1rfoori"
    "nLnk5dzthHkio9grL8RDUX0S4h0e1gurmZTGEuH2oARgk8c/StSilF8rTHKPMmj55/4Uv4s/uWf/AIEf"
    "/WrqvA3hDxv4M1B2SCyns7ggTwm49P4hxwf5165RXo1MyrVIuE0mn5HnU8so0pKcG015gKKKK809MKKK"
    "KACsTxdDqt34cubLQ7eKa4ukaFjNJsVFYEE+59q26KqMuWSl2JnHmi49z55/4Uv4s/uWf/gR/wDWr1L4"
    "caPr/hzRf7I1u3tlghLNBLDLuJ3HJUjHqTzXaUV218dVrw5JpWOGhl9KhPng3cKDRRXAegeNeOfhz4n8"
    "UeLbrUra3tY4GAjiDXHJVRgE8cZ64rAHwc8YAYH2UD2uf/rV9CUV6UMyrwioK1keXPK6E5ucm7s+fP8A"
    "hTvjH1tf/An/AOtTX+D3jEIxxbNx90XPX9K+haKv+1cR5fcT/ZOH8/vOauPCtt4g8F2Gkaz58aRwxF0i"
    "fadyrjB9cHt7V51rfwLuoyZPD+pRyr18m6G1vwYAg/iBXtVFctLGVqL9x6djqrYKjWXvrXufOLfC/wAc"
    "Rt5YsWI6ArdJj/0KtfRvgjrV3Mr63dQWMWcsqN5sh/L5R9cmvd8UV1SzXENWVl8jljlOHTu7v5mdoWhW"
    "Xh3R4dO0yPZDEOp6ux6sT3JrRoory5Scnd7nqxioqy2PIviF8P8AxJ4s8UvfWVvbR26RiKMvcfM4GeSM"
    "cdeldp8P9I1PQfCsWl6vBFFJbsdrRSbw4Jznpwea6miumpip1KSpNKyOWnhKdOq6ybuwooorlOsa5IQl"
    "V3MBwM4zXjnjLwN438Y6yL26gsYYo12Qwrc5CL9cck17LRXRh8RKhLmglc5sRh44iPLNu3keG+HPhn4w"
    "8OeILXVIrawna3bPlvccHjHpx1r3CMs0as67GIBK5zg+madRTxGJniGpTtdCw+Fhhk4wvZhRRRXMdR5z"
    "8TvC3iHxe9taaZaWgtbZvME8s2HZiMEYxwP515//AMKX8Wf3LP8A8CP/AK1fQ1FehRzCtRgoQSsjzq2X"
    "Ua03Um3dnJeCbfxRpekLp3iG2tpFtottvNFPlnx0Vhj0715rc/CvxbceIZNU+z2QL3JuPL+09Pm3Yziv"
    "d6KinjalOcpxS1LqYKnVhGE2/d2I4GkeFGmQRyFQWQNu2nuM96eRmloriO48V8YfCTVNQ8T3N14dtLaC"
    "ylIYK0+PmPLEDHAz2rtfh5omteF/C0+nalaQtLE7SQeVPkSk/wAJ4+XkdeevtXa0YrsqYyrVpKlPZHFT"
    "wVKlVdWF02eF+IPhl4z8Ra/dapdx2Qe4fOwXOQo6BenYYr2TQLeWz8P2VtPbJayQwrG0Ub7lXAxwe44z"
    "WhiiprYqdaKhJKy2KoYSnQm5xbu97hXm/wATfAmqeML6yk0qK0j+zxsrzTTFWfJBAwFPAwfzr0iis6Na"
    "VGanDc1rUY14OE9jzT4c+EPFXg28mhvDYz6dckGRUnbdGw/iUbeeOo+npWZ8Qvh/4l8WeK3v7O3tUt0i"
    "WGPfccsASckY45Jr16it1jaiq+2SVzneBpOiqLb5T57Hwb8XqMKLUD0Fz/8AWpf+FO+MfW1/8Cf/AK1f"
    "QdFdH9q4jy+45/7Jw/n9588T/CHxhFbu5jgl2qTsS4yW9hmvTPGvhrWPEvgrTtJ0xLdGCxvM1xIV27V6"
    "AAHv/Ku7orGpj6tSUZSSvE2p5fSpxlGLdpbnmXw18Ca94O1m5m1EWclvcxbGaKZiyEHI4K8074meE/FH"
    "i6+gg0sW4023XcFebaXkPUkY7DAH416XRUfXKntvbNK5f1Kn7H2Cb5T56HwY8Wg5CWYP/Xx/9anf8Kd8"
    "Y/8ATr/4E/8A1q+g6K6f7VxHl9xzf2Th/P7z57Pwe8YgE/6Mfb7T/wDWr2bwTY3Om+CtMs76IxXEEOyR"
    "D2IJreornxGNqYiKjOx0YfBUsPJyhcKKKK4juCiiigAooooAD0r561aCS11m8hmBDpM4OfrX0LXG+MPA"
    "i69N9t091gvMYcN92X0z6H3r0MDXjRm1PZnnY/DyrQThujyCtLw9bPd+JLCGIZYzofwByf5VsD4b+IzL"
    "tNtEFz98zrj+ef0ruvB/giPw6Wurt1nvWG0Mo+WMdwPf3r1a+MpRpvld2eTQwdWVRcysjk/ijp0sOvRX"
    "20mG4iChuwZe35EVw9fQ2o6ba6tZPaX8IlhfqD2PqD2NcFe/CfMjHT9SwhPCzpkj8R1/KubCY6nGmoVN"
    "LHVi8DUlUc6eqZ5tXtXw/wBQW+8H2yg5e2JhcemDkfoRXnuqfD7XNMiaVYVu4lGSYDkj/gPX8s03wZ4o"
    "PhrUnS6VjaT8SqByhHRgP6VvioxxNH927tHPhZSwtb94rJm14zsXtPEc0hB8u4xIh/DB/WsCvXJ7fS/E"
    "unLlo7mFhlJI25X6Hsa52T4dRmQ+VqDKmeA0eSPxzWOHx1OMFCpo0c2MymtKq6lHVPU42xs5dQvobWAZ"
    "eVgo9vevR/F2jSap4dMNqN0tuQ8a/wB7AwR+VWtF8OWWiKTApkmYYaZ+p9h6CteuTEYznqxlDaJ6eBy3"
    "2VCcKu8t/I8CIKsQwIIOCD2pK9k1Lwpo+qSGW6tgsrdZI22k/wBDWBefDS1ZSbC+lRuwmAYfmMV6NPMq"
    "Ml72h5VXJ8RB+5Zoy/hzqAt9ams3OFuo/l/3l5H6E0/x9oM8OoNqsCF7eYDzCP4G6c+xrC1HSdT8M6hG"
    "8oMbq26KZDlTj/PSu80Txtp2qQLBqTJbXBGGEnEb/QngfQ1nW54VViaPvJ7muH5KtF4PEPlknpc8srb8"
    "MaDPrWqR7UItomDSyEcAdcfU16V/wjmg3D+athbOTzlRwfyrVggitoRFbxrFGvRUGAKzq5mnG0FqbUMl"
    "ampVJJry6kgGAAOlFFFeIfShRRRQAUUUUAFFFFABRQelcd8NtTvdU0nVpNRuZLh4tVmijaQ52oFTCj25"
    "NAHY0UZx1rNPiPRBd/ZTrGni4zt8n7Um/PpjOaANKiuU+IOo3em6LZS2Fw8DvqEEbMhxlSeR9K3Itc0m"
    "a9NnDqllJdA4MCXCF8/7uc0AX6Ka8iRRs8rKiKMlmOABVOz1zSdQmMNhqlldSr1SG4R2H4A0AXqKr3V/"
    "Z2TRLe3cFuZm2xiWQLvPoM9TSW2o2V5A81neW9xFGxV5IpVZVI6gkHg0AWaKzrfxDot3dfZrXV7CafOP"
    "KjuUZvyBzVLxZ4tsfCmkyXVy8UlwADHaGZVklywGQDyQM5PHagDeorN0/X9M1HTDe2+oWjxRoHnaO4Vl"
    "h4yQxB4x71eiuYJrZbmGaOSB13rKjAqy4zkHpj3oAkoqn/bGmf2d/aH9o2n2LOPtPnr5fXH3s468VaEs"
    "Zi80Opj27t+eMeufSgB1FV7e/s7uzF3a3cE9sQSJo5AyHHX5hxVe28QaNe3P2ez1exuJ/wDnlFcozfkD"
    "mgDQoqvdX9nZNEL27gtzM22MSyBN7egz1NFpf2eoRtJYXUF0isUZoZA4DDqCR3oAsUUV5ve6pc6l4m8R"
    "Q6l4juNDg0lVNvHAyoHBB+diQS3OOB64oA9IorC8F6hfar4N0691ZSLuWMlyV27gGIDY9wAfxrdoAKK5"
    "D4n6je6X4KkuNNupLWfz41EkZwQC3NZd94S8V6bYT3tr45uppYI2kCTwgI2BnByx/lQB6HRXO+GfFEWp"
    "eC7LWtXmgs/NXbI8jhE3Z29T6kVs22pWN5NLDZ3lvPLDjzUilVmTPTIB4/GgCzRWfLr+jQXf2WfVrGO4"
    "JwIXuUD5/wB3Oav7htzkYxnNAC0Vnxa/o1xefZINWsZbnOPJS5Qvn/dBzVye4htYWmuZo4Yl+88jBVH4"
    "mgCSiqdjrGmapu/szUbS82/e+zzrJj64Jp97qVjpsQk1G9t7SMnAeeVUB/EmgCzRUFpfWmoQCawuobqI"
    "9JIZA6/mKnoAKKxvFmuL4d8L3upHBkjjxEp/ic8KPzNcz4A1TWbbV7vQfE91Jc3TQR3tvJKckoyjco+h"
    "4+oNAHf0VFdXdvY2z3F7PFbwR8vLK4RV7ck8Cqsuu6RBdrazarZR3DY2wvcIHOemFzmgC/RSM6ohZ2Cq"
    "BkknAFZ9v4h0W7uvs1rq9hNPnHlR3KM35A5oA0aK5TxJqN3a+N/C9rb3EkcF1LMJo1PEgCZGfxrTmjz4"
    "ut5P7bEeLZh/Ze4fvef9ZjOePpQBsUVyl78QNHs/FVrpBvLMxyI5mujdIEgZc/K3PDZGMHFaGqlLq60i"
    "eDX0sYmmDpGrri+BAIQHIzxzxnrQBt0Vymv6jd23xA8M2cFxJHb3K3PnRKflk2quM/TNdGNRsmvzYi8g"
    "N2q7jbiVfMC+u3OcUAWKKK5HX/C2t6hqVxfWHi2806BlBW1iiyqYUA87h1Iz+NAHXUV5N4O0jxN4q8PL"
    "qb+NNQtS0jJ5YTf909c7hXqRkjsbNWvLhVWNAHmlYKD7kmgCeiqVjrOmaoWGmajaXhX732edZMfkTWBq"
    "uo3cPxP0GwiuJFtZ7adpYQflcheCR7UAdZRVdNQs5L57JLuBruNdz26ygyKPUr1AqGXXNJgjmebU7ONI"
    "JPKlZ7hAI3/usc8H2NAF6iobS9tb+3E9jcw3MLdJIZA6n8RxUF9rOmaYyrqWo2lmW+6LidY8/maALtFR"
    "wzw3MKy20qSxsMq8bBlP0IrlPh5qV5qVjqz39zJcNFqUsaFznaoxgD2oA6+iqFzr2kWVyLe81Wyt5z0i"
    "luEVj+BOasXOJbCbZcCENE2JweE4+9+HWgCeiucih/4oVox4nD/uj/xOd64HP3s7scdOtZXivUL3TLPw"
    "sllqckonv4YpbiNv+PhDjJOOoNAHcUVFcXVvZwNNdzxwRL96SVwqj8TUNjq2namrHTb+1vAv3jbzLJj6"
    "4NAFuiqdxrGmWczw3eo2kEsaeY6SzqrKn94gnge9UNRaK8v9HuLbX47SIyFkhR1IvgR90HPPrxmgDboo"
    "ooAKKKKACiiigAooooAKKKKACiiigArzn4l+GolthrVlEEZWC3AUYDAnhvrnj8RXo1Z+u2gvtBvrZhnz"
    "IGA+uOP1rfD1XSqqSOfE0lVpOLPB7PULzT5N9jdTW7esbla3rP4heIrVl33i3CD+CaNTn8QAf1rmDwcG"
    "ivqJ0qc/iSZ8tCrUh8Mmj2/wp4utvEtuy7fIvIhmSHOcj+8D3FWfEmuDQ9O81FDzyHbGp6Z9T9K8p8Bz"
    "yQeNLER5/eMyMB3BU11/xElzqNnFn7sRbH1OP6V48sJBYpQ6PU9SpjqiwMqn2loc3d6tf3sxkubuV2J/"
    "vEAfQdqvaN4nv9KuF3SvPbk/PE5zx7ehrFor15Uqco8rWh8pDEVYT9pGTuevXtpa+ItDMZIaG4jDRvj7"
    "pxwfrXi88L21xJBMNskbFGHoQcGvXfByuvha18zvuK/Tca878Z232bxXeDGBIwkH4ivNy+XJVnR6H0Ga"
    "R9rh6eItq7X+auY8VzNB/qZpI/8AdYius8MeNbu1u47XVZWntpCFEj8tH757iuOpR7V6lWjCrHlkjxaG"
    "Iq0JKUGe+g5AI6UVX0/f/Zlt5v3/ACV3fXAqxXyDVnY/QYu6TCiiikMKKKKACiiigAPSuD+E3/IF1v8A"
    "7DU//oKV3hrgY/hfJbTXDaf4q1ixjnmaZoraXy13N1OAevQZ9qAOw1q6tbHQ7y51Dd9lihZpQpIJXHIG"
    "Oc15ne2txJ8N7max8L6Xp2ktbGWJri5Zpwp5D52nnkEZau50rwp9j0W903VNVvtYhvAVc3spdlUjBAJP"
    "FZ48AbtHOkXWu6hcaYqbYrZ9gCccZYDcwHYE44FAHNeJS198G/Dv2qVsyyWqvITyOMZz61s/ETQdKsPh"
    "9PNZWsNrNYeW9tJEoVkbcBwetat/4Hs9R8H2Ph64uZfs9mYyJAAGcL2Ppn2qObwKL77Pb6trV/f6dbOG"
    "jsptgU46B2ADOPqaAMTxlcz6np3g+yvmZLfU7qEXgzjfkKdp+uTVn4l6XYaZ4PXUtOt4bS90+eJrV4UC"
    "NkuFK8dsE8e1dVrvh6w8Q6WLG/RgisHieM7WiYdGU9qyT4J+2XNq+v6ze6tDZuHht5giIGHQttA3H60A"
    "YnxKs01aTwra3WQlzfBZMHBIKjIra8SQeHvC/ga7jn01RpxAVrW2JjMrEgAZBB54yc1p634dh1u80u4l"
    "meI6dceeioBhzjoam17Q7TxFo02m6grGGXHKnBUg5BFAHmPja11Kz8DRyS6BpekwQSReSYpy1xEc8Dhc"
    "Z9fmrpvifHHN8MLq4kjRpgsGJCo3DMiZwasah8PzrGk/YNY1+/vUQDyDIEHl9OTgDccDGWz1Nb2saDa6"
    "54dl0a9Z/IlRVLIcMCpBB/MCgDL1i1hh+Gl+LaGOMvpjE7FC7j5ffFSeGWH/AArPTTkYGlpk/wDbOrul"
    "6JNaaXLYanqUuqQunlqJokTamMbflAz9TWTZ+BTY2LabFr2oHSSCBZHZwDzt343Y9gRQBmeBNLi1v4Pp"
    "p1x9y5SZM4+6SxwfwPNZh129Hwn/ALHGf7Y8/wDsbywfm3Z2/wDoHeu+8NaDF4Z0GHS7eZ5o4SxDuACc"
    "nPb61nDwPYjxofEPnzb93mfZuPL8zbt3/XFAFPxFFo3hf4cR6dqlrJeWiLHbrbxOUMz5yBkEYBIya5Px"
    "rb6lZ+G9PnuNE0vSo4ruEQG3nLTxnnC8KB0HPzV6V4h0Cz8S6Q+n6hvCFg6vGcMjDowNYWoeADq9gtvr"
    "Gu3160RUwPIqDysEHOFA3EgYycnBNAGb8TrNNUk8L2lwT5dxfhHwcEgrzXb6ZpNho1oLbS7SK1hznZEu"
    "AT6n1PvVHWfDcOtXGlSzTyRnTbgToFA+cgYwa2qAI7mb7PayzFSwjQvtHU4GcV5ND4V1DxlosXjEXiT6"
    "yz+dBbSIpgCITiLBHX3P/wBevXetcpF4IbTprg+HtcvtKt7hy720apJGCepUODt/CgDD0jxdP4l8b6FB"
    "aG4szbQ3H9p2PKqjBdqgjoRkgivR64yH4bWVlqVvqem6lfW+oxuXmumk8xrjPUODxiuzHTnmgDhvi+M/"
    "D+UA4/0mLn/gVRS/DS9vYzBqnjHWLu1fiSEvgOPTkn+VdN4o8Ow+KNFbTbmd4EaRZN8YBOVOe9bFAHn/"
    "AMStNttM+Fx0+xj8q3hkhRFB6DdWjeaTaeEfh9qM2gWiQ3KWLFpUHzuwX7xPUkZJrY8TeH4fE2ivptxM"
    "8CM6vvQAn5TnvWk9vHJam3mUSRMmxlYcMMYINAHJ+GfDGiyfD60jmtIJVvLRZbiaRQzOzLuZix56n8MV"
    "leD/ALVrnwfuLOe++zsfNtormVsbVB4yfTnH0rXXwG1vYyabY6/qNtpUmc2a7DtBOSquRuUewNbJ8M6X"
    "/wAIydAW32aeYvK8tTzj1z655z60Aea6jatpHhW107xX4aMdja+WBq+kSoWyMAPyMjPvjOa2/Gs1xqPi"
    "vwvYWccF5bTJJcJHduUinYKCu4gHOBzjHetNvh+1xpsOlX/iDULnSYioFmwRcqOilwNxHtmtjXfDFnrt"
    "raxu8tpNZuHtZ7dtrwkcce3tQBylzpeqxeMtCvbiPQdIlSYoUt7lt9yhGGQKUG7irnifR9Sfxpb6zpdr"
    "ZawYLQwvptzKFZMnPmLngHoMmtaw8IiHXItX1fU7nVr23QpbtOqosIIwSFUAZ96dq3hNL/XI9ZsNRudM"
    "1FYvJaaAKwkTrhlYEH/9XpQBi+B7jT28T6ykenXmj6nIsclzYSlTEAON6YHfPP1ru6w9C8MRaPfXeoT3"
    "k+oajeYE1zPgHaOigAAKPYVuUAeYfEnVZb3xRpWh2Wn3GqJaOt7eW1spJcA/Kp/r9RWZ4j8U6oPEOj+I"
    "pPDGo6Wunv5c806na8TnBUnA9Tj3NejaR4Xg0rxBqesG4kubrUGG4yAfu1HRVx26fkK0NX0yDWtHutOv"
    "BmG5jMbY6jPQj3B5oA534kypP8MNUliYMjxRsrDuDItQ6z4f0v8A4VncA2UJdbHzfNKAuX2Z3buuc85r"
    "Tn8JR3PgX/hGbi+meLyli+0FRv2qwI9ugArSu9Kju9Ak0ppGWOS38guByBtxmgDkm1ayh+DNnd+I45b2"
    "CSziSSNZGVpicADcCDzjk1zfja11K08DxSy6BpekwQyReSYpy1xEc8DhcZ9fmr0CTwfYXPguLw3dtJLb"
    "RRLGsnAfK9G+tZuofD86xpX2HWdev71Ex5BkCDy8EcnAG44GMtnqaAIPETl/G/gl25LPKT/36qW+/wCS"
    "z6Z/2C5f/Qq2r3w5De6to9+88ivpRYooAxJldvNSTaBFN4st9eMziWC2a3EQA2kMc5oA5TV7K1Pxo0OM"
    "20JSSymZ18sYY4bkjuat+OVVNd8IIihVXUsAAYAG2tbXPCq6trNlq1rqE+nX9mrIk0Kq+VbqCrAjual1"
    "Lw4uqy6PNd3krTaXKJg4VR5zBcEkDgZ68UAct8Q5dRt/GHh2XRIkmv0gvDDG/Rm2L+Z9qv8AwzTTpdCk"
    "voJHn1WeQ/2jJP8A60S/3SOwHYdK3tQ0CLUPEWl6tJM6SaaJAkYAw+8AHP5VXj8KW9r4tbXtPuJLWSdN"
    "t1boB5c/+0R2PuP8aAN+o7j/AI9Zf9w/yqSmyLvjZDwGBFAHEfCD/kn8X/XxL/Oq/j97u78X+GtLgggu"
    "IZWlm8i6crFM6gYDEA9OuMd66jwt4dh8LaIum208k6LIz75AAeT7U7xD4ctfENvAtxJNbz20nm29zA22"
    "SJvUGgDkrvS9Vj8XaDe3EWg6RLHPsxb3LB7lDwyBSg3HHSovH0+p23jzSJtCiWW/SwujEjdzt5x6nGcD"
    "ua6aw8IiPW4dW1fVLrVry2UrbtOqosORgkKoAz71cu/D8V34p0/W2mdZbGKSNYwBtYOMEmgDF+GsWlt4"
    "aF3p8r3F5cOWv5p/9aZu4b0x29qz/BOm2d34p8Wz3dvHO8eqOqeau4IDnOAemeM/QV0dt4VgsPFU2tab"
    "cSWv2pcXNqijy5j/AHsdm9x7+pqbRPD0OiX2qXMMzytqVyblwwGEJ7D2oA5zwlCmn/EnxPp9moitNkMw"
    "hXhVYg5IHaovh9Y22rya5q+qwR3N++pSwMZlDGJFxhRnp1NdRY+HobHxPqOtJO7S36IjxkDau30qjP4O"
    "EWrXOoaFqt1pEt4c3CQqjpIf721wQD7igDI8GKun/EHxTpFj8unQtFNHGv3Y3ZQWA9OSePaq3ge4ltPC"
    "Pii4txmWK+unT6gZFdd4e8N2Xhy3mW0Ms09y/mXFzO26SZvUn+lJ4e8NweH7W8gile4W7uXuH8wDgt1H"
    "0oA574d6Hpl54Dt7m8tYbyfUA8l1LMgdnbcRgk+1Q+BpGHgvX7JZWltrG7ure1cnOYgOOfTmtRPAxsku"
    "LfRdcv8ATbC4Ys9pCEZVz12MwLJ+Bqe7g0bwV4IntldbS0SJ0UyNku7Ke/ck0AcvZf8AJvMv/XjJ/wCh"
    "GjxF/wAi74F/6/Lb+QrX8KaIdT+EVrpN6ZLcXNsyMdvzKCxOcGtW/wDCFvfWGjWr3MqLpMscsbADMhQc"
    "A/lQBzfjU3l98SNB02GC2uY1hknS3u5CkUjgHk4ByQBkcUv9lalD8QNGvbkaHpUmHR4LW5bfdJjoFKDO"
    "K6rxB4YtfEDWszzTWl5Zvvt7q3bDxnv7EexqvpvhJLbXBrOqahcarqCR+XFLOFVYlPXaqgAH3oA5jUtE"
    "std+Ngh1OFZ4IdOEvlP91yGwMjuOelaPiy3itfFHguC2jWKKO8dURBgKNnQCt9fDsK+MX8Qee/nPa/Zv"
    "KwNuM5z654p+raBFq2q6VfSzPG+mzGVFUDDkjGDQBrUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUEZGDy"
    "KKKAPFPGXhS50LU5Z4o2ewlctHIBwmf4T6Y/WuZr6C1PVdP06H/iYzIoccIRkt+Fc1/wkHhO2k8+206M"
    "zA5BS1VT+Br3aGMquGsG/M+dxOGw8Kj/AHij5Mxvh94Zls5W17VV+zwxxkwiTg8jlj6DFZ/iDVTrGsy3"
    "Iz5Y+SMHso6f1P41b17xXda0DCi+Ra5/1YOS31P9K6Lwx4Qit4kvNVjEkzcpCw4Qe47mrc/Yt16/xPRI"
    "45J41rC4b4Vq2/6+44iLTb6dA0FncSKejJExH54rZ0fwbqF9cobyJra3By5fhiPQCvTQMdOBS1xzzKpJ"
    "WirHdSyOjGSc5N/gMghjt7eOGFQscahVUdgK5rxf4V/tyFbm0wt5EMAE4Ei+h966iiuCnVnTnzx3ParU"
    "Kdam6c1oeIzaFqtvN5UmnXO72iJB/EV0fhjwRdT3kd1q8Rgt4zuEbfekPpjsK9LxRXfUzKpOPKlY8qlk"
    "1GnPmk2/IAMDAoooryz2wooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAC"
    "iiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAC"
    "iiigAooooAKKKKACiiigAooooAKKKKACiiigAoIB6jNFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABR"
    "RRQAUUUUAFFFFABUN5craWU1w/3YkLn8BU1VNVtje6TdWy/eliZR9ccVUbcyvsRUclBuO55FfX0+o3kl"
    "zcuXkc557D0HtVenOjRyMjgqynBB7Gm19fFJKyPzWTcpNy3NrwlaJeeJbZZBuVMyEHvgZH616tivOvAN"
    "lJJq8t3tIjhjK7vVj2/KvRa+fzGV61uyPsskp8uG5rbsKKKK849sKKKKACiiigAooooAKKKKACiiigAo"
    "oooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAo"
    "oooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAo"
    "oooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigDn9b8I2esTGdWNvcEc"
    "uoyG+orJg+HSrIDc35dPRI9pP4kmu2orphi60I8qlocFTLsLUnzyhqVrCwt9Ns0trOMRxr27k+pPrVmi"
    "iudtt3Z3RiorlirIKKKKQwooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
    "CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
    "CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
    "CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
    "CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
    "CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
    "CiiigAooooAKKKKACiiigAooooAKKKKAP//Z"
)
LOGO_BYTES = base64.b64decode(LOGO_B64)

FIRMA_BILGI_TXT = (
    "TA Test Analiz Sistemleri ve Kimyasal Maddeler Sanayi ve Ticaret Limited Şirketi\n"
    "Monumento Plaza d:120 Esentepe 34870 Kartal İSTANBUL tel: 0216 546 1095\n"
    "Muammer Aksoy Cad. No:81 d:126 Altınşehir 16230 Nilüfer BURSA tel: 0224 502 6203\n"
    "www.takimya.com"
)
FIRMA_HTML = (
    "<b>TA Test Analiz Sistemleri ve Kimyasal Maddeler Sanayi ve Ticaret Limited Şirketi</b><br/>"
    "Monumento Plaza d:120 Esentepe 34870 Kartal İSTANBUL tel: 0216 546 1095<br/>"
    "Muammer Aksoy Cad. No:81 d:126 Altınşehir 16230 Nilüfer BURSA tel: 0224 502 6203<br/>"
    "www.takimya.com"
)
EURO_FMT = "#,##0.00\\ [$\u20ac-1]"

# ── Ayarlar (st.session_state üzerinden kalıcı) ───────────────────────────────
AYARLAR_DOSYA = "ayarlar.json"

def ayarlari_yukle():
    varsayilan = {"iletisim_ad": "", "iletisim_tel": "", "iletisim_email": ""}
    try:
        if os.path.exists(AYARLAR_DOSYA):
            with open(AYARLAR_DOSYA, encoding="utf-8") as f:
                varsayilan.update(json.load(f))
    except Exception:
        pass
    return varsayilan

def ayarlari_kaydet(a):
    try:
        with open(AYARLAR_DOSYA, "w", encoding="utf-8") as f:
            json.dump(a, f, ensure_ascii=False, indent=2)
    except Exception:
        pass

# ── Parser ────────────────────────────────────────────────────────────────────
def urunu_ayir(metin: str) -> list:
    metin = metin.replace("\r\n", "\n").replace("\r", "\n")
    for marker in ["---- Original Message ----", "----İletilen İleti----", "----Forwarded"]:
        idx = metin.find(marker)
        if idx != -1:
            bolum = metin[idx:]
            subj_m = re.search(r"Subject:.*\n", bolum)
            metin = bolum[subj_m.end():] if subj_m else bolum
            break

    bloklar = re.compile(r"={6,}").split(metin)

    # Fiyat satırından önceki boş satırları her iki formatta da kaldır
    metin2 = re.sub(r"\n{2,}([\d]{1,3}(?:[.,]\d{3})*(?:[.,]\d{2})?|[\d]+(?:[.,]\d{2})?)\s*(?:EUR|€)",
                    r"\n\1 EUR", metin)
    bloklar = re.compile(r"={6,}").split(metin2)

    # ======= yoksa boş satırla böl
    if len(bloklar) <= 2:
        bloklar = re.split(r"\n{2,}", metin2)

    urunler = []
    for blok in bloklar:
        blok = blok.strip()
        if not blok: continue
        satirlar = [s.strip() for s in blok.splitlines() if s.strip()]
        if not satirlar: continue
        fiyat = None; fiyat_idx = None
        for i in range(len(satirlar) - 1, -1, -1):
            # Görünmez karakterleri temizle
            satir = satirlar[i].strip().replace('\xa0', ' ').replace('\u202f', ' ')
            m = re.fullmatch(r"\s*([\d]{1,3}(?:[.,]\d{3})*(?:[.,]\d{2})?|[\d]+(?:[.,]\d{2})?)\s*(?:EUR|€)\s*", satir)
            if not m:
                m = re.match(r"^([\d]{1,3}(?:[.,]\d{3})*(?:[.,]\d{2})?|[\d]+(?:[.,]\d{2})?)\s*(?:EUR|€)\s*$", satir)
            if m:
                fiyat_idx = i; raw = m.group(1)
                if "," in raw and "." in raw:
                    raw = (raw.replace(".", "").replace(",", ".")
                           if raw.index(".") < raw.index(",") else raw.replace(",", ""))
                elif "," in raw:
                    raw = raw.replace(",", ".")
                try: fiyat = float(raw)
                except: fiyat = 0.0
                break
        if fiyat is None: continue
        ic = satirlar[:fiyat_idx]
        if not ic: continue
        if any(skip in ic[0] for skip in
               ["Original Message", "İletilen", "Forwarded", "Fatih", "Sener", "takimya", "@"]):
            continue
        urunler.append({"kod": ic[0], "aciklama": "\n".join(ic), "fiyat": fiyat, "adet": 1})
    return urunler


# ── Excel & PDF ───────────────────────────────────────────────────────────────
def _thin():
    s = Side(style="thin")
    return Border(left=s, right=s, top=s, bottom=s)

def excel_olustur(urunler, musteri_adi, musteri_sehir, teklif_no, teklif_tarihi,
                  teslim_suresi, teslimat, alt_notlar, iletisim, indirim, cikti):
    wb = Workbook(); ws = wb.active; ws.title = "Sheet1"
    for col, w in [("A",7.11),("B",69.55),("C",5.66),("D",15.44),("E",15.66),("F",7.11)]:
        ws.column_dimensions[col].width = w
    ws.sheet_view.view = "normal"
    ws.sheet_view.showGridLines = False
    ws.page_setup.paperSize = 9
    ws.page_setup.orientation = "portrait"
    ws.page_setup.fitToPage = True
    ws.page_setup.fitToWidth = 1
    ws.page_setup.fitToHeight = 0
    ws.page_margins.left=0.4; ws.page_margins.right=0.48
    ws.page_margins.top=0.46; ws.page_margins.bottom=0.48
    ws.print_area = "A1:F100"

    b12  = Font(name="Calibri", size=12, bold=True)
    n12  = Font(name="Calibri", size=12)
    n11  = Font(name="Calibri", size=11)
    ctr  = Alignment(horizontal="center", vertical="center", wrap_text=True)
    ltop = Alignment(horizontal="left",   vertical="top",    wrap_text=True)
    ctop = Alignment(horizontal="center", vertical="top",    wrap_text=True)
    lmid = Alignment(horizontal="left",   vertical="center", wrap_text=True)

    # Firma başlığı
    ws.merge_cells("B2:D9")
    ws["B2"].value = FIRMA_BILGI_TXT; ws["B2"].font = b12; ws["B2"].alignment = ctr
    ws.row_dimensions[2].height = 65

    # Logo
    try:
        from openpyxl.drawing.xdr import XDRPoint2D, XDRPositiveSize2D
        from openpyxl.drawing.spreadsheet_drawing import AbsoluteAnchor
        from openpyxl.utils.units import pixels_to_EMU
        img = XLImage(io.BytesIO(LOGO_BYTES))
        img.width = 220; img.height = 56
        pos  = XDRPoint2D(pixels_to_EMU(195), pixels_to_EMU(6))
        size = XDRPositiveSize2D(pixels_to_EMU(220), pixels_to_EMU(56))
        img.anchor = AbsoluteAnchor(pos=pos, ext=size)
        ws.add_image(img)
    except Exception:
        try:
            img2 = XLImage(io.BytesIO(LOGO_BYTES)); img2.width=220; img2.height=56; img2.anchor="C1"; ws.add_image(img2)
        except: pass

    # FİYAT TEKLİFİ
    ws.merge_cells("B12:D12")
    ws["B12"].value = "FİYAT TEKLİFİ"; ws["B12"].font = b12; ws["B12"].alignment = ctr
    ws.row_dimensions[12].height = 20

    # Teklif No / Tarih / Teslim Süresi
    ws.merge_cells("C15:D15")
    ws["C15"].value = "Teklif No :"; ws["C15"].font = b12; ws["C15"].alignment = lmid
    ws["E15"].value = teklif_no; ws["E15"].font = n12; ws["E15"].alignment = lmid
    ws.merge_cells("C16:D16")
    ws["C16"].value = "Tarih :"; ws["C16"].font = b12; ws["C16"].alignment = lmid
    ws["E16"].value = teklif_tarihi; ws["E16"].font = n12; ws["E16"].alignment = lmid
    if teslim_suresi.strip():
        ws.merge_cells("C17:D17")
        ws["C17"].value = "Teslim Süresi :"; ws["C17"].font = b12; ws["C17"].alignment = lmid
        ws["E17"].value = teslim_suresi; ws["E17"].font = n12; ws["E17"].alignment = lmid
        ws.row_dimensions[17].height = 16

    # Müşteri
    ws.merge_cells("A17:B17")
    ws["A17"].value = musteri_adi.upper(); ws["A17"].font = b12; ws["A17"].alignment = ltop
    ws.merge_cells("A18:B18")
    ws["A18"].value = musteri_sehir.upper(); ws["A18"].font = b12; ws["A18"].alignment = ltop

    # Tablo başlığı
    ws.row_dimensions[21].height = 30
    for col, val in [("A","No"),("B","AÇIKLAMA"),("C","ADET"),("D","BİRİM FİYAT"),("E","TOPLAM FİYAT")]:
        c = ws[f"{col}21"]; c.value = val; c.font = n12; c.alignment = ctr; c.border = _thin()

    def rb():
        t = Side(style="thin"); return Border(left=t, right=t, top=t, bottom=t)

    DS = 25; r = DS
    for idx, urun in enumerate(urunler, 1):
        adet = urun.get("adet", 1)
        ws.row_dimensions[r].height = max(15, min(urun["aciklama"].count("\n")*13.8+13.8, 600))
        ws[f"A{r}"].value = idx;              ws[f"A{r}"].font=n12; ws[f"A{r}"].alignment=ctop; ws[f"A{r}"].border=rb()
        ws[f"B{r}"].value = urun["aciklama"]; ws[f"B{r}"].font=n11; ws[f"B{r}"].alignment=ltop; ws[f"B{r}"].border=rb()
        ws[f"C{r}"].value = adet;             ws[f"C{r}"].font=n12; ws[f"C{r}"].alignment=ctop
        ws[f"C{r}"].number_format = "#,##0";  ws[f"C{r}"].border=rb()
        # Birim fiyat D sütununda
        fv = urun["fiyat"]
        ws[f"D{r}"].value = int(fv) if fv==int(fv) else fv
        ws[f"D{r}"].font=n12; ws[f"D{r}"].alignment=ltop; ws[f"D{r}"].number_format=EURO_FMT; ws[f"D{r}"].border=rb()
        # Toplam fiyat = birim * adet
        ws[f"E{r}"].value = f"=D{r}*C{r}"
        ws[f"E{r}"].font=n12; ws[f"E{r}"].alignment=ltop; ws[f"E{r}"].number_format=EURO_FMT; ws[f"E{r}"].border=rb()
        r += 1

    # TOPLAM → İNDİRİM → NET TOPLAM
    tr = r + 1

    # 1) TOPLAM (ürünler toplamı)
    toplam_r = tr
    ws[f"B{tr}"].value = "TOPLAM"; ws[f"B{tr}"].font = b12; ws[f"B{tr}"].alignment = lmid
    ws[f"E{tr}"].value = f"=SUM(E{DS}:E{r-1})"
    ws[f"E{tr}"].font = b12; ws[f"E{tr}"].number_format = EURO_FMT
    tr += 1

    if indirim and indirim > 0:
        # 2) İNDİRİM
        indirim_r = tr
        ws[f"B{tr}"].value = "İNDİRİM"; ws[f"B{tr}"].font = b12; ws[f"B{tr}"].alignment = lmid
        ws[f"E{tr}"].value = indirim; ws[f"E{tr}"].font = b12; ws[f"E{tr}"].number_format = EURO_FMT
        tr += 1

        # 3) Net tutar (etiketsiz, sadece tutar — çizgi üstünde)
        net_r = tr
        ws[f"E{tr}"].value = f"=E{toplam_r}-E{indirim_r}"
        ws[f"E{tr}"].font = b12; ws[f"E{tr}"].number_format = EURO_FMT
        # Üstüne çizgi
        from openpyxl.styles import Border, Side as Sd
        top_border = Border(top=Sd(style="thin"))
        ws[f"E{tr}"].border = top_border
        tr += 1

    # Alt notlar + Teslimat (sol) | İletişim (sağ — D:E sütunu)
    nr = tr + 3
    # Sol: alt notlar
    sol_nr = nr
    for txt in alt_notlar:
        if txt.strip():
            ws[f"B{sol_nr}"].value = txt; ws[f"B{sol_nr}"].font = b12
            ws[f"B{sol_nr}"].alignment = Alignment(vertical="top", wrap_text=True)
            sol_nr += 2
    if teslimat.strip():
        ws[f"B{sol_nr}"].value = f"Teslimat: {teslimat}"; ws[f"B{sol_nr}"].font = b12
        ws[f"B{sol_nr}"].alignment = Alignment(vertical="top", wrap_text=True); sol_nr += 2

    # Sağ: iletişim — D:E sütunlarında, nr satırından başla
    if iletisim.strip():
        il_nr = nr
        ws[f"D{il_nr}"].value = "İletişim:"; ws[f"D{il_nr}"].font = b12
        ws[f"D{il_nr}"].alignment = Alignment(vertical="top", wrap_text=True); il_nr += 1
        for satir in iletisim.strip().splitlines():
            ws.merge_cells(f"D{il_nr}:E{il_nr}")
            ws[f"D{il_nr}"].value = satir; ws[f"D{il_nr}"].font = n12
            ws[f"D{il_nr}"].alignment = Alignment(vertical="top", wrap_text=True); il_nr += 1

    wb.save(cikti)
    return len(urunler)

def _reg_pdf_fonts():
    candidates = [
        ("/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
         "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"),
        (r"C:\Windows\Fonts\arial.ttf",   r"C:\Windows\Fonts\arialbd.ttf"),
        (r"C:\Windows\Fonts\calibri.ttf", r"C:\Windows\Fonts\calibrib.ttf"),
    ]
    for reg, bold in candidates:
        if os.path.exists(reg) and os.path.exists(bold):
            try:
                pdfmetrics.registerFont(TTFont("Sans",     reg))
                pdfmetrics.registerFont(TTFont("SansBold", bold))
                return ("Sans", "SansBold")
            except: continue
    return ("Helvetica", "Helvetica-Bold")

def _fmt_euro(val):
    if val == 0: return "0,00 \u20ac"
    s = f"{val:,.2f}".replace(",","X").replace(".",",").replace("X",".")
    return f"{s} \u20ac"

def pdf_olustur(urunler, musteri_adi, musteri_sehir, teklif_no, teklif_tarihi,
                teslim_suresi, teslimat, alt_notlar, iletisim, indirim, cikti):
    if not HAS_PDF:
        raise ImportError("pip install reportlab")
    FONT, FONT_BOLD = _reg_pdf_fonts()
    PW, PH = A4; MAR = 1.5*cm; CW = PW - 2*MAR
    doc = BaseDocTemplate(cikti, pagesize=A4,
                          leftMargin=MAR, rightMargin=MAR,
                          topMargin=MAR, bottomMargin=MAR)
    frame = Frame(MAR, MAR, CW, PH-2*MAR, id="normal")
    doc.addPageTemplates([PageTemplate(id="main", frames=frame)])
    story = []

    def sty(name, **kw):
        d = dict(fontName=FONT, fontSize=9, leading=12, spaceAfter=0, spaceBefore=0)
        d.update(kw); return ParagraphStyle(name, **d)
    def para(text, style):
        text = str(text).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\n","<br/>")
        return Paragraph(text, style)
    def hpara(html, style):
        return Paragraph(html, style)

    S_FIRMA = sty("firma", fontName=FONT_BOLD, fontSize=8, alignment=TA_CENTER, leading=13)
    S_BOLD  = sty("bold",  fontName=FONT_BOLD)
    S_ACK   = sty("ack",   fontSize=8, leading=11)
    S_SM    = sty("sm",    fontSize=8, leading=11)

    # Logo + başlık
    logo_img = RLImage(io.BytesIO(LOGO_BYTES), width=7*cm, height=1.8*cm)
    logo_img.hAlign = "CENTER"
    firma_p = Paragraph(FIRMA_HTML, S_FIRMA)
    hdr = Table([[logo_img], [firma_p]], colWidths=[CW])
    hdr.setStyle(TableStyle([
        ("ALIGN",(0,0),(-1,-1),"CENTER"),
        ("BOTTOMPADDING",(0,0),(0,0),4),
        ("BOTTOMPADDING",(0,1),(0,1),8),
    ]))
    story += [hdr,
              HRFlowable(width=CW, thickness=1, color=colors.black),
              Spacer(1, 3*mm),
              hpara("<b>FİYAT TEKLİFİ</b>",
                    sty("fth", fontName=FONT_BOLD, fontSize=11, alignment=TA_CENTER)),
              Spacer(1, 3*mm)]

    # Müşteri + Teklif No/Tarih/Teslim
    meta = [
        [hpara(f"<b>{musteri_adi.upper()}</b>", S_BOLD),
         hpara(f"<b>Teklif No :</b>  {teklif_no}", sty("mn1", fontName=FONT_BOLD, alignment=TA_RIGHT))],
        [hpara(f"<b>{musteri_sehir.upper()}</b>", S_BOLD),
         hpara(f"<b>Tarih :</b>  {teklif_tarihi}", sty("mn2", fontName=FONT_BOLD, alignment=TA_RIGHT))],
    ]
    if teslim_suresi.strip():
        meta.append(["", hpara(f"<b>Teslim Süresi :</b>  {teslim_suresi}", sty("mn3", fontName=FONT_BOLD, alignment=TA_RIGHT))])
    mt = Table(meta, colWidths=[CW*0.6, CW*0.4])
    mt.setStyle(TableStyle([("VALIGN",(0,0),(-1,-1),"TOP"),("BOTTOMPADDING",(0,0),(-1,-1),1),("TOPPADDING",(0,0),(-1,-1),1)]))
    story += [mt, Spacer(1, 4*mm)]

    # Ürün tablosu
    C0=0.8*cm; C2=1.3*cm; C3=2.8*cm; C4=2.8*cm; C1=CW-C0-C2-C3-C4
    tbl = [[
        hpara("<b>No</b>",           sty("h0",fontName=FONT_BOLD,fontSize=8,alignment=TA_CENTER,leading=10)),
        hpara("<b>AÇIKLAMA</b>",     sty("h1",fontName=FONT_BOLD,fontSize=9,alignment=TA_CENTER,leading=11)),
        hpara("<b>ADET</b>",         sty("h2",fontName=FONT_BOLD,fontSize=8,alignment=TA_CENTER,leading=10)),
        hpara("<b>BİRİM FİYAT</b>",  sty("h3",fontName=FONT_BOLD,fontSize=8,alignment=TA_CENTER,leading=10)),
        hpara("<b>TOPLAM FİYAT</b>", sty("h4",fontName=FONT_BOLD,fontSize=8,alignment=TA_CENTER,leading=10)),
    ]]
    toplam = 0
    for i, urun in enumerate(urunler, 1):
        fv = urun["fiyat"]; adet = urun.get("adet",1); toplam += fv * adet
        tbl.append([
            para(str(i),             sty(f"n{i}", alignment=TA_CENTER, fontSize=8)),
            para(urun["aciklama"],   S_ACK),
            para(str(adet),          sty(f"a{i}", alignment=TA_CENTER, fontSize=8)),
            para(_fmt_euro(fv),      sty(f"b{i}", alignment=TA_RIGHT,  fontSize=8)),
            para(_fmt_euro(fv*adet), sty(f"p{i}", alignment=TA_RIGHT,  fontSize=8)),
        ])
    if indirim and indirim > 0:
        tbl.append(["","","",
            hpara("<b>TOPLAM</b>", sty("tt",fontName=FONT_BOLD,alignment=TA_CENTER)),
            hpara(f"<b>{_fmt_euro(toplam)}</b>", sty("tp",fontName=FONT_BOLD,alignment=TA_CENTER)),
        ])
        tbl.append(["","","",
            hpara("<b>İNDİRİM</b>", sty("ind2",fontName=FONT_BOLD,alignment=TA_CENTER)),
            hpara(f"<b>{_fmt_euro(indirim)}</b>", sty("indp2",fontName=FONT_BOLD,alignment=TA_CENTER)),
        ])
        toplam_net = toplam - indirim
        tbl.append(["","","","",
            hpara(f"<b>{_fmt_euro(toplam_net)}</b>", sty("net",fontName=FONT_BOLD,alignment=TA_CENTER)),
        ])
    else:
        toplam_net = toplam
        tbl.append(["","","",
            hpara("<b>TOPLAM</b>", sty("tt",fontName=FONT_BOLD,alignment=TA_CENTER)),
            hpara(f"<b>{_fmt_euro(toplam_net)}</b>", sty("tp",fontName=FONT_BOLD,alignment=TA_CENTER)),
        ])
    NR = len(tbl)
    t = Table(tbl, colWidths=[C0,C1,C2,C3,C4], repeatRows=1,
              rowHeights=[20]+[None]*(NR-1))
    t.setStyle(TableStyle([
        ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#d9d9d9")),
        ("VALIGN",(0,0),(-1,0),"MIDDLE"),
        ("TOPPADDING",(0,0),(-1,0),5),("BOTTOMPADDING",(0,0),(-1,0),5),
        ("VALIGN",(0,1),(-1,-2),"TOP"),
        ("TOPPADDING",(0,1),(-1,-2),4),("BOTTOMPADDING",(0,1),(-1,-2),4),
        ("LEFTPADDING",(1,1),(1,-1),4),
        ("TOPPADDING",(0,-1),(-1,-1),5),("BOTTOMPADDING",(0,-1),(-1,-1),5),
        ("LINEABOVE",(0,-1),(-1,-1),1,colors.black),
        ("BOX",(0,0),(-1,-1),0.5,colors.black),
        ("INNERGRID",(0,0),(-1,-1),0.3,colors.HexColor("#cccccc")),
        *[("BACKGROUND",(0,r),(-1,r),colors.HexColor("#f7f7f7")) for r in range(2,NR-1,2)],
    ]))
    story += [t, Spacer(1, 5*mm)]

    # Alt notlar + Teslimat (sol) | İletişim (sağ) — yan yana tablo
    sol_items = []
    for txt in alt_notlar:
        if txt.strip():
            sol_items.append(hpara(f"<b>{txt}</b>", S_BOLD))
    if teslimat.strip():
        sol_items.append(Spacer(1, 2*mm))
        sol_items.append(hpara(f"<b>Teslimat:</b>  {teslimat}", S_BOLD))

    sag_items = []
    if iletisim.strip():
        sag_items.append(hpara("<b>İletişim:</b>", S_BOLD))
        for satir in iletisim.strip().splitlines():
            sag_items.append(para(satir, S_SM))

    # Eşit uzunlukta yap
    max_len = max(len(sol_items), len(sag_items), 1)
    while len(sol_items) < max_len: sol_items.append(Spacer(1, 1*mm))
    while len(sag_items) < max_len: sag_items.append(Spacer(1, 1*mm))

    from reportlab.platypus import KeepInFrame
    sol_frame  = KeepInFrame(CW*0.55, 200, sol_items)
    sag_frame  = KeepInFrame(CW*0.4,  200, sag_items)

    footer_tbl = Table([[sol_frame, sag_frame]], colWidths=[CW*0.62, CW*0.38])
    footer_tbl.setStyle(TableStyle([
        ("VALIGN", (0,0), (-1,-1), "TOP"),
        ("ALIGN",  (1,0), (1,0),  "LEFT"),
    ]))
    story.append(footer_tbl)

    doc.build(story)
    return len(urunler)


# ── Streamlit UI ──────────────────────────────────────────────────────────────
st.set_page_config(page_title="Fiyat Teklifi Oluşturucu | TA Test Analiz",
                   page_icon="📊", layout="wide")

# Logo + başlık
col_logo, col_title = st.columns([1, 4])
with col_logo:
    st.image(LOGO_BYTES, width=180)
with col_title:
    st.markdown("## Fiyat Teklifi Oluşturucu")

st.divider()

# Ayarlar sidebar
with st.sidebar:
    st.markdown("### ⚙️ İletişim Ayarları")
    if "ayarlar" not in st.session_state:
        st.session_state.ayarlar = ayarlari_yukle()
    a = st.session_state.ayarlar
    a["iletisim_ad"]    = st.text_input("Ad Soyad",  a.get("iletisim_ad",""))
    a["iletisim_tel"]   = st.text_input("Telefon",   a.get("iletisim_tel",""))
    a["iletisim_email"] = st.text_input("E-posta",   a.get("iletisim_email",""))
    if st.button("💾 Kaydet"):
        ayarlari_kaydet(a)
        st.success("Kaydedildi!")

# Ana layout
col_sol, col_sag = st.columns([1.2, 1])

with col_sol:
    st.markdown("#### 📋 Ürün Listesi")
    metin = st.text_area("Ürün listesini yapıştırın", height=400, label_visibility="collapsed")

with col_sag:
    st.markdown("#### ⚙️ Teklif Bilgileri")
    musteri_adi   = st.text_input("Müşteri Adı")
    musteri_sehir = st.text_input("Müşteri Şehri")
    teklif_no     = st.text_input("Teklif No")
    teklif_tarihi = st.text_input("Teklif Tarihi", value=date.today().strftime("%d/%m/%Y"))
    teslim_suresi = st.text_input("Teslim Süresi")
    teslimat      = st.text_input("Teslimat", value="Müşteri Tesisleri")
    indirim_str   = st.text_input("İndirim (€)", value="")
    st.markdown("---")
    not1 = st.text_input("Alt Not 1", value="K.D.V. hariçtir.")
    not2 = st.text_input("Alt Not 2", value="Fiyatlarımız EURO cinsindendir.")
    not3 = st.text_input("Alt Not 3", value="Ödeme: Peşin")
    not4 = st.text_input("Alt Not 4", value="")

# İletişim metni
def iletisim_metni():
    a = st.session_state.get("ayarlar", {})
    satirlar = [v for v in [a.get("iletisim_ad",""), a.get("iletisim_tel",""), a.get("iletisim_email","")] if v]
    return "\n".join(satirlar)

# Önizle
if st.button("🔍 Ürünleri Önizle / Adet Düzenle", use_container_width=True):
    if not metin.strip():
        st.warning("Önce ürün listesini yapıştırın.")
    else:
        urunler = urunu_ayir(metin)
        if not urunler:
            st.error("Hiç ürün bulunamadı. Format: her blok EUR ile bitmeli, bloklar ====== ile ayrılmalı.")
        else:
            st.session_state["urunler"] = urunler
            st.success(f"{len(urunler)} ürün bulundu. Aşağıdan adet düzenleyebilirsiniz.")

if "urunler" in st.session_state:
    st.markdown("#### Ürün Listesi — Adet Düzenle")
    urunler = st.session_state["urunler"]
    for i, urun in enumerate(urunler):
        c1, c2, c3 = st.columns([3, 1, 1])
        with c1:
            st.text(urun["aciklama"].splitlines()[0][:60])
        with c2:
            st.text(f"{urun['fiyat']:,.2f} €")
        with c3:
            urun["adet"] = st.number_input(f"Adet", min_value=1, value=urun.get("adet",1),
                                            key=f"adet_{i}", label_visibility="collapsed")
    st.session_state["urunler"] = urunler

st.divider()

# Ortak parametreler
def get_kw():
    indirim = 0.0
    if indirim_str.strip():
        try: indirim = float(indirim_str.replace(",","."))
        except: pass
    urunler = st.session_state.get("urunler", urunu_ayir(metin) if metin.strip() else [])
    return dict(
        urunler       = urunler,
        musteri_adi   = musteri_adi,
        musteri_sehir = musteri_sehir,
        teklif_no     = teklif_no,
        teklif_tarihi = teklif_tarihi,
        teslim_suresi = teslim_suresi,
        teslimat      = teslimat,
        alt_notlar    = [n for n in [not1,not2,not3,not4] if n.strip()],
        iletisim      = iletisim_metni(),
        indirim       = indirim,
    )

musteri_dosya = re.sub(r'[\\/:*?"<>|]', "_", musteri_adi or "Teklif")

col_b1, col_b2, col_b3 = st.columns(3)

with col_b1:
    if st.button("📊 Excel Oluştur", use_container_width=True, type="primary"):
        kw = get_kw()
        if not kw["urunler"]:
            st.error("Hiç ürün bulunamadı.")
        else:
            buf = io.BytesIO()
            excel_olustur(**kw, cikti=buf)
            buf.seek(0)
            st.download_button("⬇️ Excel İndir", buf,
                               file_name=f"Teklif_{musteri_dosya}.xlsx",
                               mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                               use_container_width=True)

with col_b2:
    if st.button("📄 PDF Oluştur", use_container_width=True, type="primary"):
        kw = get_kw()
        if not kw["urunler"]:
            st.error("Hiç ürün bulunamadı.")
        elif not HAS_PDF:
            st.error("reportlab kurulu değil.")
        else:
            buf = io.BytesIO()
            pdf_olustur(**kw, cikti=buf)
            buf.seek(0)
            st.download_button("⬇️ PDF İndir", buf,
                               file_name=f"Teklif_{musteri_dosya}.pdf",
                               mime="application/pdf",
                               use_container_width=True)

with col_b3:
    if st.button("📦 Excel + PDF", use_container_width=True):
        kw = get_kw()
        if not kw["urunler"]:
            st.error("Hiç ürün bulunamadı.")
        else:
            buf_x = io.BytesIO()
            excel_olustur(**kw, cikti=buf_x); buf_x.seek(0)
            st.download_button("⬇️ Excel İndir", buf_x,
                               file_name=f"Teklif_{musteri_dosya}.xlsx",
                               mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                               use_container_width=True)
            if HAS_PDF:
                buf_p = io.BytesIO()
                pdf_olustur(**kw, cikti=buf_p); buf_p.seek(0)
                st.download_button("⬇️ PDF İndir", buf_p,
                                   file_name=f"Teklif_{musteri_dosya}.pdf",
                                   mime="application/pdf",
                                   use_container_width=True)
